# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = E:\Code\XNEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = E:\Code\XNEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Code\XNEngine\CMakeFiles E:\Code\XNEngine\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Code\XNEngine\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xne

# Build rule for target.
xne: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 xne
.PHONY : xne

# fast build rule for target.
xne/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/build
.PHONY : xne/fast

src/core/buffer.obj: src/core/buffer.c.obj
.PHONY : src/core/buffer.obj

# target to build an object file
src/core/buffer.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/core/buffer.c.obj
.PHONY : src/core/buffer.c.obj

src/core/buffer.i: src/core/buffer.c.i
.PHONY : src/core/buffer.i

# target to preprocess a source file
src/core/buffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/core/buffer.c.i
.PHONY : src/core/buffer.c.i

src/core/buffer.s: src/core/buffer.c.s
.PHONY : src/core/buffer.s

# target to generate assembly for a file
src/core/buffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/core/buffer.c.s
.PHONY : src/core/buffer.c.s

src/core/compression.obj: src/core/compression.c.obj
.PHONY : src/core/compression.obj

# target to build an object file
src/core/compression.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/core/compression.c.obj
.PHONY : src/core/compression.c.obj

src/core/compression.i: src/core/compression.c.i
.PHONY : src/core/compression.i

# target to preprocess a source file
src/core/compression.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/core/compression.c.i
.PHONY : src/core/compression.c.i

src/core/compression.s: src/core/compression.c.s
.PHONY : src/core/compression.s

# target to generate assembly for a file
src/core/compression.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/core/compression.c.s
.PHONY : src/core/compression.c.s

src/core/file.obj: src/core/file.c.obj
.PHONY : src/core/file.obj

# target to build an object file
src/core/file.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/core/file.c.obj
.PHONY : src/core/file.c.obj

src/core/file.i: src/core/file.c.i
.PHONY : src/core/file.i

# target to preprocess a source file
src/core/file.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/core/file.c.i
.PHONY : src/core/file.c.i

src/core/file.s: src/core/file.c.s
.PHONY : src/core/file.s

# target to generate assembly for a file
src/core/file.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/core/file.c.s
.PHONY : src/core/file.c.s

src/core/str.obj: src/core/str.c.obj
.PHONY : src/core/str.obj

# target to build an object file
src/core/str.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/core/str.c.obj
.PHONY : src/core/str.c.obj

src/core/str.i: src/core/str.c.i
.PHONY : src/core/str.i

# target to preprocess a source file
src/core/str.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/core/str.c.i
.PHONY : src/core/str.c.i

src/core/str.s: src/core/str.c.s
.PHONY : src/core/str.s

# target to generate assembly for a file
src/core/str.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/core/str.c.s
.PHONY : src/core/str.c.s

src/engine/engine.obj: src/engine/engine.cpp.obj
.PHONY : src/engine/engine.obj

# target to build an object file
src/engine/engine.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/engine/engine.cpp.obj
.PHONY : src/engine/engine.cpp.obj

src/engine/engine.i: src/engine/engine.cpp.i
.PHONY : src/engine/engine.i

# target to preprocess a source file
src/engine/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/engine/engine.cpp.i
.PHONY : src/engine/engine.cpp.i

src/engine/engine.s: src/engine/engine.cpp.s
.PHONY : src/engine/engine.s

# target to generate assembly for a file
src/engine/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/engine/engine.cpp.s
.PHONY : src/engine/engine.cpp.s

src/engine/model.obj: src/engine/model.cpp.obj
.PHONY : src/engine/model.obj

# target to build an object file
src/engine/model.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/engine/model.cpp.obj
.PHONY : src/engine/model.cpp.obj

src/engine/model.i: src/engine/model.cpp.i
.PHONY : src/engine/model.i

# target to preprocess a source file
src/engine/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/engine/model.cpp.i
.PHONY : src/engine/model.cpp.i

src/engine/model.s: src/engine/model.cpp.s
.PHONY : src/engine/model.s

# target to generate assembly for a file
src/engine/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/engine/model.cpp.s
.PHONY : src/engine/model.cpp.s

src/engine/sprite.obj: src/engine/sprite.cpp.obj
.PHONY : src/engine/sprite.obj

# target to build an object file
src/engine/sprite.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/engine/sprite.cpp.obj
.PHONY : src/engine/sprite.cpp.obj

src/engine/sprite.i: src/engine/sprite.cpp.i
.PHONY : src/engine/sprite.i

# target to preprocess a source file
src/engine/sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/engine/sprite.cpp.i
.PHONY : src/engine/sprite.cpp.i

src/engine/sprite.s: src/engine/sprite.cpp.s
.PHONY : src/engine/sprite.s

# target to generate assembly for a file
src/engine/sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/engine/sprite.cpp.s
.PHONY : src/engine/sprite.cpp.s

src/engine/transform.obj: src/engine/transform.cpp.obj
.PHONY : src/engine/transform.obj

# target to build an object file
src/engine/transform.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/engine/transform.cpp.obj
.PHONY : src/engine/transform.cpp.obj

src/engine/transform.i: src/engine/transform.cpp.i
.PHONY : src/engine/transform.i

# target to preprocess a source file
src/engine/transform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/engine/transform.cpp.i
.PHONY : src/engine/transform.cpp.i

src/engine/transform.s: src/engine/transform.cpp.s
.PHONY : src/engine/transform.s

# target to generate assembly for a file
src/engine/transform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/engine/transform.cpp.s
.PHONY : src/engine/transform.cpp.s

src/graphics/camera.obj: src/graphics/camera.cpp.obj
.PHONY : src/graphics/camera.obj

# target to build an object file
src/graphics/camera.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/camera.cpp.obj
.PHONY : src/graphics/camera.cpp.obj

src/graphics/camera.i: src/graphics/camera.cpp.i
.PHONY : src/graphics/camera.i

# target to preprocess a source file
src/graphics/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/camera.cpp.i
.PHONY : src/graphics/camera.cpp.i

src/graphics/camera.s: src/graphics/camera.cpp.s
.PHONY : src/graphics/camera.s

# target to generate assembly for a file
src/graphics/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/camera.cpp.s
.PHONY : src/graphics/camera.cpp.s

src/graphics/device.obj: src/graphics/device.cpp.obj
.PHONY : src/graphics/device.obj

# target to build an object file
src/graphics/device.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/device.cpp.obj
.PHONY : src/graphics/device.cpp.obj

src/graphics/device.i: src/graphics/device.cpp.i
.PHONY : src/graphics/device.i

# target to preprocess a source file
src/graphics/device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/device.cpp.i
.PHONY : src/graphics/device.cpp.i

src/graphics/device.s: src/graphics/device.cpp.s
.PHONY : src/graphics/device.s

# target to generate assembly for a file
src/graphics/device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/device.cpp.s
.PHONY : src/graphics/device.cpp.s

src/graphics/framebuffer.obj: src/graphics/framebuffer.cpp.obj
.PHONY : src/graphics/framebuffer.obj

# target to build an object file
src/graphics/framebuffer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/framebuffer.cpp.obj
.PHONY : src/graphics/framebuffer.cpp.obj

src/graphics/framebuffer.i: src/graphics/framebuffer.cpp.i
.PHONY : src/graphics/framebuffer.i

# target to preprocess a source file
src/graphics/framebuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/framebuffer.cpp.i
.PHONY : src/graphics/framebuffer.cpp.i

src/graphics/framebuffer.s: src/graphics/framebuffer.cpp.s
.PHONY : src/graphics/framebuffer.s

# target to generate assembly for a file
src/graphics/framebuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/framebuffer.cpp.s
.PHONY : src/graphics/framebuffer.cpp.s

src/graphics/graphics.obj: src/graphics/graphics.cpp.obj
.PHONY : src/graphics/graphics.obj

# target to build an object file
src/graphics/graphics.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/graphics.cpp.obj
.PHONY : src/graphics/graphics.cpp.obj

src/graphics/graphics.i: src/graphics/graphics.cpp.i
.PHONY : src/graphics/graphics.i

# target to preprocess a source file
src/graphics/graphics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/graphics.cpp.i
.PHONY : src/graphics/graphics.cpp.i

src/graphics/graphics.s: src/graphics/graphics.cpp.s
.PHONY : src/graphics/graphics.s

# target to generate assembly for a file
src/graphics/graphics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/graphics.cpp.s
.PHONY : src/graphics/graphics.cpp.s

src/graphics/mesh.obj: src/graphics/mesh.cpp.obj
.PHONY : src/graphics/mesh.obj

# target to build an object file
src/graphics/mesh.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/mesh.cpp.obj
.PHONY : src/graphics/mesh.cpp.obj

src/graphics/mesh.i: src/graphics/mesh.cpp.i
.PHONY : src/graphics/mesh.i

# target to preprocess a source file
src/graphics/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/mesh.cpp.i
.PHONY : src/graphics/mesh.cpp.i

src/graphics/mesh.s: src/graphics/mesh.cpp.s
.PHONY : src/graphics/mesh.s

# target to generate assembly for a file
src/graphics/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/mesh.cpp.s
.PHONY : src/graphics/mesh.cpp.s

src/graphics/shader.obj: src/graphics/shader.cpp.obj
.PHONY : src/graphics/shader.obj

# target to build an object file
src/graphics/shader.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/shader.cpp.obj
.PHONY : src/graphics/shader.cpp.obj

src/graphics/shader.i: src/graphics/shader.cpp.i
.PHONY : src/graphics/shader.i

# target to preprocess a source file
src/graphics/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/shader.cpp.i
.PHONY : src/graphics/shader.cpp.i

src/graphics/shader.s: src/graphics/shader.cpp.s
.PHONY : src/graphics/shader.s

# target to generate assembly for a file
src/graphics/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/shader.cpp.s
.PHONY : src/graphics/shader.cpp.s

src/graphics/texture.obj: src/graphics/texture.cpp.obj
.PHONY : src/graphics/texture.obj

# target to build an object file
src/graphics/texture.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/texture.cpp.obj
.PHONY : src/graphics/texture.cpp.obj

src/graphics/texture.i: src/graphics/texture.cpp.i
.PHONY : src/graphics/texture.i

# target to preprocess a source file
src/graphics/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/texture.cpp.i
.PHONY : src/graphics/texture.cpp.i

src/graphics/texture.s: src/graphics/texture.cpp.s
.PHONY : src/graphics/texture.s

# target to generate assembly for a file
src/graphics/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/texture.cpp.s
.PHONY : src/graphics/texture.cpp.s

src/graphics/ui/ui.obj: src/graphics/ui/ui.cpp.obj
.PHONY : src/graphics/ui/ui.obj

# target to build an object file
src/graphics/ui/ui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/ui/ui.cpp.obj
.PHONY : src/graphics/ui/ui.cpp.obj

src/graphics/ui/ui.i: src/graphics/ui/ui.cpp.i
.PHONY : src/graphics/ui/ui.i

# target to preprocess a source file
src/graphics/ui/ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/ui/ui.cpp.i
.PHONY : src/graphics/ui/ui.cpp.i

src/graphics/ui/ui.s: src/graphics/ui/ui.cpp.s
.PHONY : src/graphics/ui/ui.s

# target to generate assembly for a file
src/graphics/ui/ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/graphics/ui/ui.cpp.s
.PHONY : src/graphics/ui/ui.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\xne.dir\build.make CMakeFiles/xne.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... xne
	@echo ... src/core/buffer.obj
	@echo ... src/core/buffer.i
	@echo ... src/core/buffer.s
	@echo ... src/core/compression.obj
	@echo ... src/core/compression.i
	@echo ... src/core/compression.s
	@echo ... src/core/file.obj
	@echo ... src/core/file.i
	@echo ... src/core/file.s
	@echo ... src/core/str.obj
	@echo ... src/core/str.i
	@echo ... src/core/str.s
	@echo ... src/engine/engine.obj
	@echo ... src/engine/engine.i
	@echo ... src/engine/engine.s
	@echo ... src/engine/model.obj
	@echo ... src/engine/model.i
	@echo ... src/engine/model.s
	@echo ... src/engine/sprite.obj
	@echo ... src/engine/sprite.i
	@echo ... src/engine/sprite.s
	@echo ... src/engine/transform.obj
	@echo ... src/engine/transform.i
	@echo ... src/engine/transform.s
	@echo ... src/graphics/camera.obj
	@echo ... src/graphics/camera.i
	@echo ... src/graphics/camera.s
	@echo ... src/graphics/device.obj
	@echo ... src/graphics/device.i
	@echo ... src/graphics/device.s
	@echo ... src/graphics/framebuffer.obj
	@echo ... src/graphics/framebuffer.i
	@echo ... src/graphics/framebuffer.s
	@echo ... src/graphics/graphics.obj
	@echo ... src/graphics/graphics.i
	@echo ... src/graphics/graphics.s
	@echo ... src/graphics/mesh.obj
	@echo ... src/graphics/mesh.i
	@echo ... src/graphics/mesh.s
	@echo ... src/graphics/shader.obj
	@echo ... src/graphics/shader.i
	@echo ... src/graphics/shader.s
	@echo ... src/graphics/texture.obj
	@echo ... src/graphics/texture.i
	@echo ... src/graphics/texture.s
	@echo ... src/graphics/ui/ui.obj
	@echo ... src/graphics/ui/ui.i
	@echo ... src/graphics/ui/ui.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

