# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = E:\Code\MDreams\Source

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = E:\Code\MDreams\Source

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /d E:\Code\MDreams\Source && $(CMAKE_COMMAND) -E cmake_progress_start E:\Code\MDreams\Source\CMakeFiles E:\Code\MDreams\Source\extern\xnengine\\CMakeFiles\progress.marks
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 extern/xnengine/all
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Code\MDreams\Source\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 extern/xnengine/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 extern/xnengine/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 extern/xnengine/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /d E:\Code\MDreams\Source && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
extern/xnengine/CMakeFiles/xne.dir/rule:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 extern/xnengine/CMakeFiles/xne.dir/rule
.PHONY : extern/xnengine/CMakeFiles/xne.dir/rule

# Convenience name for target.
xne: extern/xnengine/CMakeFiles/xne.dir/rule
.PHONY : xne

# fast build rule for target.
xne/fast:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/build
.PHONY : xne/fast

src/core/buffer.obj: src/core/buffer.c.obj
.PHONY : src/core/buffer.obj

# target to build an object file
src/core/buffer.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/core/buffer.c.obj
.PHONY : src/core/buffer.c.obj

src/core/buffer.i: src/core/buffer.c.i
.PHONY : src/core/buffer.i

# target to preprocess a source file
src/core/buffer.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/core/buffer.c.i
.PHONY : src/core/buffer.c.i

src/core/buffer.s: src/core/buffer.c.s
.PHONY : src/core/buffer.s

# target to generate assembly for a file
src/core/buffer.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/core/buffer.c.s
.PHONY : src/core/buffer.c.s

src/core/compression.obj: src/core/compression.c.obj
.PHONY : src/core/compression.obj

# target to build an object file
src/core/compression.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/core/compression.c.obj
.PHONY : src/core/compression.c.obj

src/core/compression.i: src/core/compression.c.i
.PHONY : src/core/compression.i

# target to preprocess a source file
src/core/compression.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/core/compression.c.i
.PHONY : src/core/compression.c.i

src/core/compression.s: src/core/compression.c.s
.PHONY : src/core/compression.s

# target to generate assembly for a file
src/core/compression.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/core/compression.c.s
.PHONY : src/core/compression.c.s

src/core/debug.obj: src/core/debug.c.obj
.PHONY : src/core/debug.obj

# target to build an object file
src/core/debug.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/core/debug.c.obj
.PHONY : src/core/debug.c.obj

src/core/debug.i: src/core/debug.c.i
.PHONY : src/core/debug.i

# target to preprocess a source file
src/core/debug.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/core/debug.c.i
.PHONY : src/core/debug.c.i

src/core/debug.s: src/core/debug.c.s
.PHONY : src/core/debug.s

# target to generate assembly for a file
src/core/debug.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/core/debug.c.s
.PHONY : src/core/debug.c.s

src/core/file.obj: src/core/file.c.obj
.PHONY : src/core/file.obj

# target to build an object file
src/core/file.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/core/file.c.obj
.PHONY : src/core/file.c.obj

src/core/file.i: src/core/file.c.i
.PHONY : src/core/file.i

# target to preprocess a source file
src/core/file.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/core/file.c.i
.PHONY : src/core/file.c.i

src/core/file.s: src/core/file.c.s
.PHONY : src/core/file.s

# target to generate assembly for a file
src/core/file.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/core/file.c.s
.PHONY : src/core/file.c.s

src/core/string.obj: src/core/string.c.obj
.PHONY : src/core/string.obj

# target to build an object file
src/core/string.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/core/string.c.obj
.PHONY : src/core/string.c.obj

src/core/string.i: src/core/string.c.i
.PHONY : src/core/string.i

# target to preprocess a source file
src/core/string.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/core/string.c.i
.PHONY : src/core/string.c.i

src/core/string.s: src/core/string.c.s
.PHONY : src/core/string.s

# target to generate assembly for a file
src/core/string.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/core/string.c.s
.PHONY : src/core/string.c.s

src/engine/engine.obj: src/engine/engine.c.obj
.PHONY : src/engine/engine.obj

# target to build an object file
src/engine/engine.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/engine/engine.c.obj
.PHONY : src/engine/engine.c.obj

src/engine/engine.i: src/engine/engine.c.i
.PHONY : src/engine/engine.i

# target to preprocess a source file
src/engine/engine.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/engine/engine.c.i
.PHONY : src/engine/engine.c.i

src/engine/engine.s: src/engine/engine.c.s
.PHONY : src/engine/engine.s

# target to generate assembly for a file
src/engine/engine.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/engine/engine.c.s
.PHONY : src/engine/engine.c.s

src/engine/grid.obj: src/engine/grid.c.obj
.PHONY : src/engine/grid.obj

# target to build an object file
src/engine/grid.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/engine/grid.c.obj
.PHONY : src/engine/grid.c.obj

src/engine/grid.i: src/engine/grid.c.i
.PHONY : src/engine/grid.i

# target to preprocess a source file
src/engine/grid.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/engine/grid.c.i
.PHONY : src/engine/grid.c.i

src/engine/grid.s: src/engine/grid.c.s
.PHONY : src/engine/grid.s

# target to generate assembly for a file
src/engine/grid.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/engine/grid.c.s
.PHONY : src/engine/grid.c.s

src/engine/model.obj: src/engine/model.c.obj
.PHONY : src/engine/model.obj

# target to build an object file
src/engine/model.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/engine/model.c.obj
.PHONY : src/engine/model.c.obj

src/engine/model.i: src/engine/model.c.i
.PHONY : src/engine/model.i

# target to preprocess a source file
src/engine/model.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/engine/model.c.i
.PHONY : src/engine/model.c.i

src/engine/model.s: src/engine/model.c.s
.PHONY : src/engine/model.s

# target to generate assembly for a file
src/engine/model.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/engine/model.c.s
.PHONY : src/engine/model.c.s

src/engine/scene.obj: src/engine/scene.c.obj
.PHONY : src/engine/scene.obj

# target to build an object file
src/engine/scene.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/engine/scene.c.obj
.PHONY : src/engine/scene.c.obj

src/engine/scene.i: src/engine/scene.c.i
.PHONY : src/engine/scene.i

# target to preprocess a source file
src/engine/scene.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/engine/scene.c.i
.PHONY : src/engine/scene.c.i

src/engine/scene.s: src/engine/scene.c.s
.PHONY : src/engine/scene.s

# target to generate assembly for a file
src/engine/scene.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/engine/scene.c.s
.PHONY : src/engine/scene.c.s

src/engine/sprite.obj: src/engine/sprite.c.obj
.PHONY : src/engine/sprite.obj

# target to build an object file
src/engine/sprite.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/engine/sprite.c.obj
.PHONY : src/engine/sprite.c.obj

src/engine/sprite.i: src/engine/sprite.c.i
.PHONY : src/engine/sprite.i

# target to preprocess a source file
src/engine/sprite.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/engine/sprite.c.i
.PHONY : src/engine/sprite.c.i

src/engine/sprite.s: src/engine/sprite.c.s
.PHONY : src/engine/sprite.s

# target to generate assembly for a file
src/engine/sprite.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/engine/sprite.c.s
.PHONY : src/engine/sprite.c.s

src/engine/transform.obj: src/engine/transform.c.obj
.PHONY : src/engine/transform.obj

# target to build an object file
src/engine/transform.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/engine/transform.c.obj
.PHONY : src/engine/transform.c.obj

src/engine/transform.i: src/engine/transform.c.i
.PHONY : src/engine/transform.i

# target to preprocess a source file
src/engine/transform.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/engine/transform.c.i
.PHONY : src/engine/transform.c.i

src/engine/transform.s: src/engine/transform.c.s
.PHONY : src/engine/transform.s

# target to generate assembly for a file
src/engine/transform.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/engine/transform.c.s
.PHONY : src/engine/transform.c.s

src/graphics/camera.obj: src/graphics/camera.c.obj
.PHONY : src/graphics/camera.obj

# target to build an object file
src/graphics/camera.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/camera.c.obj
.PHONY : src/graphics/camera.c.obj

src/graphics/camera.i: src/graphics/camera.c.i
.PHONY : src/graphics/camera.i

# target to preprocess a source file
src/graphics/camera.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/camera.c.i
.PHONY : src/graphics/camera.c.i

src/graphics/camera.s: src/graphics/camera.c.s
.PHONY : src/graphics/camera.s

# target to generate assembly for a file
src/graphics/camera.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/camera.c.s
.PHONY : src/graphics/camera.c.s

src/graphics/device.obj: src/graphics/device.c.obj
.PHONY : src/graphics/device.obj

# target to build an object file
src/graphics/device.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/device.c.obj
.PHONY : src/graphics/device.c.obj

src/graphics/device.i: src/graphics/device.c.i
.PHONY : src/graphics/device.i

# target to preprocess a source file
src/graphics/device.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/device.c.i
.PHONY : src/graphics/device.c.i

src/graphics/device.s: src/graphics/device.c.s
.PHONY : src/graphics/device.s

# target to generate assembly for a file
src/graphics/device.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/device.c.s
.PHONY : src/graphics/device.c.s

src/graphics/framebuffer.obj: src/graphics/framebuffer.c.obj
.PHONY : src/graphics/framebuffer.obj

# target to build an object file
src/graphics/framebuffer.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/framebuffer.c.obj
.PHONY : src/graphics/framebuffer.c.obj

src/graphics/framebuffer.i: src/graphics/framebuffer.c.i
.PHONY : src/graphics/framebuffer.i

# target to preprocess a source file
src/graphics/framebuffer.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/framebuffer.c.i
.PHONY : src/graphics/framebuffer.c.i

src/graphics/framebuffer.s: src/graphics/framebuffer.c.s
.PHONY : src/graphics/framebuffer.s

# target to generate assembly for a file
src/graphics/framebuffer.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/framebuffer.c.s
.PHONY : src/graphics/framebuffer.c.s

src/graphics/graphics.obj: src/graphics/graphics.c.obj
.PHONY : src/graphics/graphics.obj

# target to build an object file
src/graphics/graphics.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/graphics.c.obj
.PHONY : src/graphics/graphics.c.obj

src/graphics/graphics.i: src/graphics/graphics.c.i
.PHONY : src/graphics/graphics.i

# target to preprocess a source file
src/graphics/graphics.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/graphics.c.i
.PHONY : src/graphics/graphics.c.i

src/graphics/graphics.s: src/graphics/graphics.c.s
.PHONY : src/graphics/graphics.s

# target to generate assembly for a file
src/graphics/graphics.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/graphics.c.s
.PHONY : src/graphics/graphics.c.s

src/graphics/light.obj: src/graphics/light.c.obj
.PHONY : src/graphics/light.obj

# target to build an object file
src/graphics/light.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/light.c.obj
.PHONY : src/graphics/light.c.obj

src/graphics/light.i: src/graphics/light.c.i
.PHONY : src/graphics/light.i

# target to preprocess a source file
src/graphics/light.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/light.c.i
.PHONY : src/graphics/light.c.i

src/graphics/light.s: src/graphics/light.c.s
.PHONY : src/graphics/light.s

# target to generate assembly for a file
src/graphics/light.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/light.c.s
.PHONY : src/graphics/light.c.s

src/graphics/mesh.obj: src/graphics/mesh.c.obj
.PHONY : src/graphics/mesh.obj

# target to build an object file
src/graphics/mesh.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/mesh.c.obj
.PHONY : src/graphics/mesh.c.obj

src/graphics/mesh.i: src/graphics/mesh.c.i
.PHONY : src/graphics/mesh.i

# target to preprocess a source file
src/graphics/mesh.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/mesh.c.i
.PHONY : src/graphics/mesh.c.i

src/graphics/mesh.s: src/graphics/mesh.c.s
.PHONY : src/graphics/mesh.s

# target to generate assembly for a file
src/graphics/mesh.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/mesh.c.s
.PHONY : src/graphics/mesh.c.s

src/graphics/shader.obj: src/graphics/shader.c.obj
.PHONY : src/graphics/shader.obj

# target to build an object file
src/graphics/shader.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/shader.c.obj
.PHONY : src/graphics/shader.c.obj

src/graphics/shader.i: src/graphics/shader.c.i
.PHONY : src/graphics/shader.i

# target to preprocess a source file
src/graphics/shader.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/shader.c.i
.PHONY : src/graphics/shader.c.i

src/graphics/shader.s: src/graphics/shader.c.s
.PHONY : src/graphics/shader.s

# target to generate assembly for a file
src/graphics/shader.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/shader.c.s
.PHONY : src/graphics/shader.c.s

src/graphics/texture.obj: src/graphics/texture.c.obj
.PHONY : src/graphics/texture.obj

# target to build an object file
src/graphics/texture.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/texture.c.obj
.PHONY : src/graphics/texture.c.obj

src/graphics/texture.i: src/graphics/texture.c.i
.PHONY : src/graphics/texture.i

# target to preprocess a source file
src/graphics/texture.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/texture.c.i
.PHONY : src/graphics/texture.c.i

src/graphics/texture.s: src/graphics/texture.c.s
.PHONY : src/graphics/texture.s

# target to generate assembly for a file
src/graphics/texture.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/texture.c.s
.PHONY : src/graphics/texture.c.s

src/graphics/ui/font.obj: src/graphics/ui/font.c.obj
.PHONY : src/graphics/ui/font.obj

# target to build an object file
src/graphics/ui/font.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/ui/font.c.obj
.PHONY : src/graphics/ui/font.c.obj

src/graphics/ui/font.i: src/graphics/ui/font.c.i
.PHONY : src/graphics/ui/font.i

# target to preprocess a source file
src/graphics/ui/font.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/ui/font.c.i
.PHONY : src/graphics/ui/font.c.i

src/graphics/ui/font.s: src/graphics/ui/font.c.s
.PHONY : src/graphics/ui/font.s

# target to generate assembly for a file
src/graphics/ui/font.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/ui/font.c.s
.PHONY : src/graphics/ui/font.c.s

src/graphics/ui/uix.obj: src/graphics/ui/uix.c.obj
.PHONY : src/graphics/ui/uix.obj

# target to build an object file
src/graphics/ui/uix.c.obj:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/ui/uix.c.obj
.PHONY : src/graphics/ui/uix.c.obj

src/graphics/ui/uix.i: src/graphics/ui/uix.c.i
.PHONY : src/graphics/ui/uix.i

# target to preprocess a source file
src/graphics/ui/uix.c.i:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/ui/uix.c.i
.PHONY : src/graphics/ui/uix.c.i

src/graphics/ui/uix.s: src/graphics/ui/uix.c.s
.PHONY : src/graphics/ui/uix.s

# target to generate assembly for a file
src/graphics/ui/uix.c.s:
	cd /d E:\Code\MDreams\Source && $(MAKE) $(MAKESILENT) -f extern\xnengine\CMakeFiles\xne.dir\build.make extern/xnengine/CMakeFiles/xne.dir/src/graphics/ui/uix.c.s
.PHONY : src/graphics/ui/uix.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... xne
	@echo ... src/core/buffer.obj
	@echo ... src/core/buffer.i
	@echo ... src/core/buffer.s
	@echo ... src/core/compression.obj
	@echo ... src/core/compression.i
	@echo ... src/core/compression.s
	@echo ... src/core/debug.obj
	@echo ... src/core/debug.i
	@echo ... src/core/debug.s
	@echo ... src/core/file.obj
	@echo ... src/core/file.i
	@echo ... src/core/file.s
	@echo ... src/core/string.obj
	@echo ... src/core/string.i
	@echo ... src/core/string.s
	@echo ... src/engine/engine.obj
	@echo ... src/engine/engine.i
	@echo ... src/engine/engine.s
	@echo ... src/engine/grid.obj
	@echo ... src/engine/grid.i
	@echo ... src/engine/grid.s
	@echo ... src/engine/model.obj
	@echo ... src/engine/model.i
	@echo ... src/engine/model.s
	@echo ... src/engine/scene.obj
	@echo ... src/engine/scene.i
	@echo ... src/engine/scene.s
	@echo ... src/engine/sprite.obj
	@echo ... src/engine/sprite.i
	@echo ... src/engine/sprite.s
	@echo ... src/engine/transform.obj
	@echo ... src/engine/transform.i
	@echo ... src/engine/transform.s
	@echo ... src/graphics/camera.obj
	@echo ... src/graphics/camera.i
	@echo ... src/graphics/camera.s
	@echo ... src/graphics/device.obj
	@echo ... src/graphics/device.i
	@echo ... src/graphics/device.s
	@echo ... src/graphics/framebuffer.obj
	@echo ... src/graphics/framebuffer.i
	@echo ... src/graphics/framebuffer.s
	@echo ... src/graphics/graphics.obj
	@echo ... src/graphics/graphics.i
	@echo ... src/graphics/graphics.s
	@echo ... src/graphics/light.obj
	@echo ... src/graphics/light.i
	@echo ... src/graphics/light.s
	@echo ... src/graphics/mesh.obj
	@echo ... src/graphics/mesh.i
	@echo ... src/graphics/mesh.s
	@echo ... src/graphics/shader.obj
	@echo ... src/graphics/shader.i
	@echo ... src/graphics/shader.s
	@echo ... src/graphics/texture.obj
	@echo ... src/graphics/texture.i
	@echo ... src/graphics/texture.s
	@echo ... src/graphics/ui/font.obj
	@echo ... src/graphics/ui/font.i
	@echo ... src/graphics/ui/font.s
	@echo ... src/graphics/ui/uix.obj
	@echo ... src/graphics/ui/uix.i
	@echo ... src/graphics/ui/uix.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /d E:\Code\MDreams\Source && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

